Mail_Alert/mailalert/main/routes.py
import os
import csv
import json
import pandas as pd
from jira import JIRA
from mailalert import db
from flask import render_template, Blueprint, request, flash, redirect, url_for, jsonify
from flask_login import login_required, current_user
from mailalert.main.forms import ComposeEmailForm, CreateMessageForm, NewIssueForm
from mailalert.models import SentMail, Student, Hall, Utils
from mailalert.main.utils import clean_student_data, validate_student_data, \
    update_student_data, error_columns, allowed_file, is_active

main = Blueprint('main', __name__)


@main.route("/get_halls", methods=['GET'])
def get_halls():
    """
    get all of the halls in the database

    Return: 
        JSON object of all the halls to ajax request
    """
    hall_list = Hall.query.filter_by(active=True)
    hall_list = [hall.name for hall in hall_list]
    # remove the current users hall because it is already being displayed
    hall_list.remove(current_user.hall.name)
    return jsonify({'halls': hall_list})


@main.route("/change_working_hall", methods=['POST'])
@login_required
def change_working_hall():
    """
    Change the current users working hall 

    Return: 
        JSON to ajax request
        "success" if hall was successfully changed
        "error" if the hall being changed to does not
        exist
    """
    new_hall = request.form.get('new_hall', None)
    hall = Hall.query.filter_by(name=new_hall, active=True).first()
    if hall:
        current_user.hall = hall
        db.session.commit()
    else:
        flash(f'Error changing to {new_hall}', 'danger')
    return jsonify({'success': 'success'})


@main.route("/upload_csv", methods=['POST'])
@login_required
def upload_csv():
    """
    Update student and employee database with most recent 
    information via csv upload. Create error csv file with 
    any students or employees that failed to upload 

    Return: 
        JSON to ajax request
        on success -
            new_student_count
            hall_update_count
            room_update_count
            new_employee_count 
            removed_employee_count
            error_count
            error_values - all of the errors in a list
            error_columns - the column names of the errors
        on error -
            json object with appropriate error message
    """
    columns = ['USERNAME', 'FIRST NAME', 'LAST NAME',
               'BUILDING', 'ROOM', 'ID NUMBER',
               'PHONE NUMBER', 'ARD', 'ALIAS', 'DR']

    # check if the post request has the file part
    if 'file' not in request.files:
        return jsonify({'error': 'No File Selected'})
    # get the file the user selected
    file = request.files['file']
    if file.filename == '':
        return jsonify({'error': 'No File Selected'})

    if file and allowed_file(file.filename):
        error_count = 0
        error_values = []

        try:
            students = file.read().decode('utf-8')
            # check if file is empty
            if not students:
                return jsonify({'error': 'File is Empty'})
            # remove all "" from fields
            students = students.replace('\"', "")
            # getting rid of \n at end of line, to make it compatible with windows and linux
            students = students.replace('\n', "")
            # split on return character and make into list
            students = students.split('\r')
            # move list into a pandas dataframe
            student_df = pd.DataFrame([student.split(',')
                                       for student in students], columns=columns)
            # make an error dataframe to add errors to
            error_df = pd.DataFrame()

            student_df = clean_student_data(student_df)
            student_df, error_df = validate_student_data(student_df, error_df)
            student_df, error_df, new_student_count, hall_update_count, room_update_count, new_employee_count, removed_employee_count = update_student_data(
                student_df, error_df)
            if new_student_count == -1:
                return jsonify({'error': 'You must set an active employment code before adding students or employees'})
            deactived_students_count = is_active(student_df)

            # check if there were any errors
            if not error_df.empty:
                error_count = error_df['USERNAME'].count()
                # reorder error_df columns
                error_df = error_df[error_columns]
                # convert df to list so it can be passed to client
                error_values = error_df.values.tolist()
            return jsonify({'new_student_count': new_student_count,
                            'hall_update_count': hall_update_count,
                            'room_update_count': room_update_count,
                            'new_employee_count': new_employee_count,
                            'removed_employee_count': removed_employee_count,
                            'deactived_students_count': deactived_students_count,
                            'error_count': str(error_count),
                            'error_values': error_values,
                            'error_columns': error_columns})
        except KeyError as err:
            return jsonify({'error': f'csv format error: {str(err)}'})
        except AssertionError as err:
            return jsonify({'error': f'Number of columns error: {str(err)}'})
        except Exception as err:
            return jsonify({'error': f'An unexpected error occurred: {str(err)}'})
    else:
        return jsonify({'error': 'That file type is not supported'})


@main.route("/feedback", methods=['GET', 'POST'])
@login_required
def feedback():
    """
    recieve bugs new feature requests reported by users
    and send them to Jira  

    Return: 
        render feedback.html
    """
    form = NewIssueForm()
    if form.validate_on_submit():
        options = {'server': 'https://mailalert.atlassian.net'}
        jira = JIRA(options, basic_auth=('corey2232@gmail.com',
                                         'sIcygfuR6RqdHbbnsziT5C0D'))
        jira.create_issue(project='MA', summary=form.summary.data, description=form.description.data,
                          priority={'name': form.priority.data}, issuetype={'name': form.issueType.data})

        flash(f'Your feedback has been sent to the development team!', 'success')
        return redirect(url_for('main.feedback'))
    return render_template('feedback.html', title='Feedback', form=form)

Mail_Alert/mailalert/templates/composeEmail.html
{% extends "layout_with_navbar.html" %}
{%block content %}

<h3 class="text-center">Select a Message</h3>
<form method='POST'>
    {{ composeEmailForm.hidden_tag() }}
    <div class="form-row mb-3">
        <label for="to" class="btn btn-secondary">To:</label>
        <div class="col-10 col-sm-11">
            {% if composeEmailForm.recipient_email.errors %}
                {{ composeEmailForm.recipient_email(class="form-control form-control-md is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in composeEmailForm.recipient_email.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{ composeEmailForm.recipient_email(class="form-control form-control-md") }}
            {% endif %}
        </div>
    </div>
    <div class="form-row mb-3">
        <label for="cc" class="btn btn-secondary">CC:</label>
        <div class="col-10 col-sm-11">
            {% if composeEmailForm.cc_recipient.errors %}
                {{ composeEmailForm.cc_recipient(class="form-control form-control-md is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in composeEmailForm.cc_recipient.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{ composeEmailForm.cc_recipient(class="form-control form-control-md") }}
            {% endif %}
        </div>
    </div>
    <div class="btn-group-toggle" data-toggle="buttons">
        {% for message in messages %}
            <label class="btn btn-outline-secondary btn-lg btn-block" style="white-space:normal;">
                <input type="radio" name="options" id="option{{ message.id }}" value="{{ message.id }}"> {{ message.content }}
            </label>
        {% endfor %}
    </div>
    <div class="row">
        {% if current_user.allowed('Building Director') %}
            <a class="btn edit mt-3" data-toggle="modal" data-target="#newMessageModal" href="">
                <i class="fas fa-plus fa-2x"></i>
            </a>
            <a class="btn edit mt-3" name="deleteMessage" data-toggle="modal" data-target="#deleteMessageModal" href="">
                <i class="fas fa-trash-alt fa-2x"></i>
            </a>
        {% endif %}
        <div class="mt-3 offset-lg-10 offset-md-8">
            {{ composeEmailForm.compose_submit(class="btn btn-success", style="visibility:hidden;") }}
        </div>
    </div>   
</form>

<!-- New Message Modal -->
<div class="modal fade" id="newMessageModal" tabindex="-1" role="dialog" aria-labelledby="newMessageModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="newMessageModalLabel">Create New Message</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="{{ url_for('main.create_message') }}" method='POST'>
                {{ createMessageForm.hidden_tag() }}
                <div class="modal-body">
                    {% if createMessageForm.new_message.errors %}
                        {{ createMessageForm.new_message(class="form-control form-control-md is-invalid", rows="10", cols="20") }}
                        <div class="invalid-feedback">
                            {% for error in form.new_message.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ createMessageForm.new_message(class="form-control form-control-md", rows="10", cols="20") }}
                    {% endif %}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    {{ createMessageForm.create_submit(class="btn btn-success")}}
                </div>
            </form>
        </div>
    </div>
</div>  

<!-- Delete Message Modal -->
<div id="deleteMessageModal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Delete Message</h4>
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to delete this Message?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <form action="{{ url_for('main.delete_message') }}" method='POST'>
                    <input type="hidden" name="deleteVal" value="">
                    <input type="submit" name="deleteMessage" class="btn btn-danger" value="Delete">
                </form>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    // once a message has been choosen the send button will become visible
    $("label").click(function(){
        $("input[name='compose_submit']").css('visibility', 'visible');
    }); 

    // gets the value of the selected radio button and changes the value of
    // the hidden field in the delete modal to the radio button selection
    $(document).ready(function(){
        $("a[name='deleteMessage']").click(function(){
            var radioValue = $("input[name='options']:checked").val();
            $("input[name='deleteVal']").val(radioValue);
        });   
    });
</script>
{% endblock %}

Mail_Alert/mailalert/templates/feedback.html
{% extends "layout_with_navbar.html" %}
{% block content %}

<h2>Feedback</h2>
<div style="font-size:large">Please use as much detail as possible when filling out this page. Such as, what page you were on, what you were trying to do, 
        if there were any prompts, etc. Also, please put your name in the Description field!
</div>

<br>
<form method="POST" action="">
    <!-- CSRF token for form submission -->
    {{ form.hidden_tag() }}

    {{ form.summary(class="form-control form-control-lg", placeholder='Reason for Feedback') }}
    <br>

    <br>
    {{ form.description(class="form-control form-control-lg", placeholder='Description') }}
        
    <br>
    {{ form.issueType.label(class="form-control-label") }}
    {{ form.issueType }}
    <br>
    {{ form.priority.label(class="form-control-label") }}
    {{ form.priority }}
    <br>
    {{ form.submit(class="btn btn-outline-info") }}


</form>
{% endblock content %}

Mail_Alert/mailalert/templates/home.html
{% extends "layout_with_navbar.html" %}
{%block content %}

<form action="" method="POST" onsubmit="parseCardSwipe()">
    {{ student_search_form.hidden_tag() }}
    <div class="card" style="width:500px; margin:10px auto;">
        <div class="card-body">
            <div class="row">
                <div class="col-9">
                    {{ student_search_form.student_id(class="form-control form-control-md", placeholder='Search for Student') }}
                    <div id='search-error' class="invalid-feedback" style='display:none;'>
                        <span></span>
                    </div>
                </div>
                <div class="col-3">
                    {{ student_search_form.submit(class="btn btn-success") }}
                </div>
            </div>
        </div>
    </div>
</form>

{% if perishables %}
<form id=pickup_form>
    <div class="perishables">
        <h2 class=text-center>Perishables</h2>
        <div class='fixed-header'>
            <table id="packagesTable" class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th>Package&nbsp;#</th>
                        <th>Name</th>
                        <th>Room</th>
                        <th>Description</th>
                        <th id="deliveryDateLabel">Delivered</th>
                        <th>Time</th>
                        <th>Phone Number</th>
                        <th>Pick&nbsp;Up</th>
                    </tr>
                </thead>
                <tbody>
                    {% for perishable in perishables %}
                        <tr class="table-danger" data-status="{{ perishable.status }}">
                            <td>{{ perishable.id }}</td>
                            <td>{{ perishable.owner.first_name }} {{ perishable.owner.last_name }}</td>
                            <td>{{ perishable.owner.room_number }}</td>
                            <td>{{ perishable.description }}</td>
                            <td>{{ perishable.delivery_date | datetimefilter("%m-%d-%Y") }}</td>
                            <td>{{ perishable.delivery_date | datetimefilter("%-I:%M %p") }}</td>
                            <td class="phone_number">{{ perishable.phone.phone_number }}</td>
                            <td>
                                <label class="checkbox-container">
                                    {{ package_pickup_form.pick_up(class="form-control form-control-md", value=perishable.id) }}
                                    <span class="checkmark"></span>
                                </label>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

    <!-- Pickup Package Modal -->
    <div id="pickupPackageModal" class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Pickup Package</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                </div>
                <div class="modal-body">
                    <p>Please enter student ID to confirm pickup</p>
                    {{ package_pickup_form.student_id_confirm(class="form-control form-control-md", placeholder="Student ID") }}
                    <div id='errorDiv' class="invalid-feedback" style='display:none;'>
                        <span id='errorAlert'></span>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    {{ package_pickup_form.confirm(class="btn btn-success") }}
                </div>
            </div>
        </div>
    </div>
    <!-- End Pickup Package Modal -->
</form>

<script>
document.getElementById("student_id_confirm").addEventListener("change", cardReader2); 
function cardReader2(){
    var card_data = document.getElementById("student_id_confirm").value;
    var details = card_data.split("^");
    var card_number = details[0];
    var regular = /[0-9]{9}|([a-zA-Z]+){3,}/g;
    var found = card_number.match(regular);
    if (found){
        document.getElementById("student_id_confirm").value = found;
    }
}
</script>
{% endif %}

<script>
// add styling to phone number
$('.phone_number').text(function(i, text) {
    return text.replace(/(\d{3})(\d{3})(\d{4})/, '$1-$2-$3');
});

// display pick up package modal when a checkbox is checked
$('input[name="pick_up"]').click(function(){
    $('#pickupPackageModal').modal('show');
});

// focus on pickup modal when it loads
$('#pickupPackageModal').on('shown.bs.modal', function() {
    $('#student_id_confirm').focus();
});

// if pick up package modal disappears uncheck the checkbox
$('#pickupPackageModal').on('hide.bs.modal', function (e) {
    $('input[name="pick_up"]').prop('checked', false); 
});


// post package pickup through ajax
$('#pickup_form').submit(function (e) {
    var url = "{{ url_for('packages._pickup_package') }}"; // send the form data here.
    $.ajax({
        type: "POST",
        url: url,
        data: $('#pickup_form').serialize(), // serializes the form's elements.
    })
    .done(function(data){
        if (data.error) {
            $('#student_id_confirm').addClass('is-invalid');
            $('#errorDiv').show();
            $('#errorAlert').text(data.error);
        } else {
            window.location.href = '/';
        }
    });
    e.preventDefault(); // block the traditional submission of the form.
});

// Inject our CSRF token into our AJAX request.
var csrf_token = "{{ csrf_token() }}";

$.ajaxSetup({
    beforeSend: function(xhr, settings) {
        if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type) && !this.crossDomain) {
            xhr.setRequestHeader("X-CSRFToken", csrf_token);
        }
    }
});

function parseCardSwipe(){
    var card_data = document.getElementById("student_id").value;
    var details = card_data.split("^");
    var card_number = details[0];
    // var regular = /[0-9]{9}/g;
    var regular = /[0-9]{9}|([a-zA-Z]+){3,}/g;
    var found = card_number.match(regular);
    document.getElementById("student_id").value = found;
}
</script>

<!-- Jquery for Search Box -->
<script src="{{ url_for('static', filename='search_box.js') }}"></script> 

{% endblock %}

Mail_Alert/mailalert/templates/layout_with_navbar.html
<!DOCTYPE html>
<html>
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Google fonts -->
  <link href="https://fonts.googleapis.com/css?family=Alatsi&display=swap" rel="stylesheet"> 

  <!-- Jquery -->
  <script src="//ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
  
  <!-- cdn to make buttons dragable -->
  <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto|Varela+Round">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>

  <!-- jquery autocomplete   -->
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

  <!-- formatting phone numbers include -->
  <script src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/3/jquery.inputmask.bundle.js"></script>

  <!-- fontawesome icons -->
  <script src="https://kit.fontawesome.com/a7232715ba.js"></script>
  
  <link rel='icon' href="{{ url_for('static', filename='favicon.png') }}">
  
  {% if title %}
  <title>Mail Alert - {{ title }}</title>
  {% else %}
  <title>Mail Alert</title>
  {% endif %}
  
</head>
{% if current_user.is_authenticated %}
<body class = body>
  <header class="site-header">
    <nav class="navbar navbar-expand-lg fixed-top">
      <!-- Mail Alert Logo -->
      <a class="navbar-brand" href="/">
        <img src="{{ url_for('static', filename='logo-dark.png') }}" alt="Mail Alert" border="0" width="150px" height="50px">
      </a>
      <!-- Collapse button -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          {% if current_user.allowed('Building Director')%}
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('admin.index') }}">Admin<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('employees.management') }}">Management<span class="sr-only">(current)</span></a>
            </li>
          {% endif %}
        </ul>

        <ul class="navbar-nav mx-auto">
          <li class="nav-item"><h3 class="working-hall">{{current_user.hall.name}}</h3></li>
        </ul>

        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('packages.home') }}">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('packages.newPackage') }}">New Package<span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item dropdown">
            <a class="user-link" href="#" id="currentUserDropDown" data-toggle="dropdown"
              aria-haspopup="true" aria-expanded="false">
            <div class="user-icon">
              <img src="{{ url_for('static', filename='user-circle-solid.svg') }}" alt="user-icon">
            </div>
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="currentUserDropDown">
              <span class="dropdown-item"> {{ current_user.first_name }} {{ current_user.last_name }} </span>
              <span class="dropdown-item">{{ current_user.access }}</span>
              <div class="dropdown-item">
                <div class="form-group">
                  <label>Working Hall</label>
                  <select class="form-control" id="change-working-hall">
                    <option class="active">{{current_user.hall.name}}</option>
                  </select>
                </div>
              </div>  
              <a id="logout" class="dropdown-item" href="{{ url_for('employees.logout') }}">Logout</a>
              <a class="dropdown-item" href="{{ url_for('employees.reset_password') }}">Reset Password</a>
            </div>
          </li>
        </ul>
      </div>
    </nav>
  </header>
  <div class = main>
  <main role="main" class="container">
    <div class="content">
    <div class="row">
      <div class="col-md-12">
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
        {% for category, message in messages %}
        <div class="alert alert-{{ category }} text-center" name="flashMessage" width="15%">
          {{ message }}
        </div>
        {% endfor %}
        {% endif %}
        {% endwith %}
        {% block content %}{% endblock %}
      </div>
    </div>
    </div>
  </main>
  </div>
<footer class ="footer">
    <div style="background-color:#DCDCDC;">
    <!-- Footer Links -->
    <div class="container text-center text-md-left mt-5">
  
      <!-- Grid row -->
      <div class="row mt-3">
  
        <!-- Grid column -->
        <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
  
          <!-- Content -->
          <div class="footerPicPadding">
            <a class="navbar-brand" href="/">
              <img src="{{ url_for('static', filename='redenv.png') }}" alt="Mail Alert" border="0" width="145px" height="145px">
            </a>
          </div>
          <div class="footer-copyright text-left py-3">© 2020 Copyright:
            <a class= "color" href="https://getmailalert.com"> getmailalert.com</a>
          </div>
        </div>
        <!-- Grid column -->
  
        <!-- Grid column -->
        <div class="col-md-3 col-lg-4 col-xl-4 mx-auto mb-4"> 
           <!-- Links -->
          <h5 class="titles">Useful links</h5>
           <div class = "links">        
              <p>
                <a class="color" href="#!">Site Sources</a><span style="padding-left:56px"></span>
                <a class="color" href="#!">Info Page</a>
              </p>
              <p>
                <a class="color" href="#!">Terms of Use</a><span style="padding-left:52px"></span>
                <a class="color" href="#!">Contact Us</a> 
              </p>
              <p>
                <a class="color" href="#!">Privacy Policy</a>
              </p>
            </div>
        </div>
        <!-- Grid column -->
        <div class="col-md-6 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
  
          <!-- Links -->
          <h5 class="titles">Site Resources</h5>
          <div class="links">
            <p><a class="color" href="#!">Help</a></p>
            <p><a class="color" href="{{ url_for('main.feedback') }}">Feedback</a></p>
          </div>
        </div>
        <!-- Grid column -->
  
      </div>
      <!-- Grid row -->
    </div>
  </div>
</footer>
</body>
{% endif %}

<script>
var url = window.location;
// remove previously active nav item
$('.navbar .nav').find('.active').removeClass('active');
// find which link is now active 
$('.nav-link').each(function () {
  if (this.href == url) {
      $(this).addClass('active');
  }
}); 

$("document").ready(function() {
  // set timeout for flash messages
  setTimeout(function() {
    $('[name="flashMessage"]').delay(3000).slideUp(300);
  });

  // prevent dropdown for current user from closing on click
  $('.dropdown-menu').on('click', function(event){
      event.stopPropagation();
  });

  // is triggered when local storage is changed in browser
  // looks to see if a user logged out of another open tab
  // if they did, log them out of all other open tabs
  window.addEventListener('storage', function(event){
    if (event.key == 'logout-event') { 
      window.location.href = "{{ url_for('employees.logout') }}"
    }
  });

  // change local storage value when user goes to logout
  $('#logout').click(function(){
    localStorage.setItem('logout-event', 'logout' + Math.random());
  });


  // populate hall options in current user dropdown 
  $('#currentUserDropDown').one('click', function(e) {
    var url = "{{ url_for('main.get_halls') }}"; // send the form data here.
    $.ajax({
      type: 'GET',
      url: url
    }).done(function(data) {
      var i;
      for (i = 0; i < data.halls.length; i++){
        $('#change-working-hall').append("<option>" + data.halls[i] + "</option>");
      }
    });
    e.preventDefault(); // block the traditional submission of the form.
  });

  // if user selects new working hall 
  $('#change-working-hall').change(function(){
    var url = "{{ url_for('main.change_working_hall') }}"; // send the form data here.
    $.ajax({
      type: 'POST',
      url: url,
      data: { new_hall: $(this).val() }
    }).done(function(data) {
      location.href = '/';
    });
  });

  // Inject our CSRF token into our AJAX request.
  var csrf_token = '{{ csrf_token() }}';
  $.ajaxSetup({
      beforeSend : function(xhr, settings) {
          if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type) && !this.crossDomain) {
              xhr.setRequestHeader('X-CSRFToken', csrf_token);
          }
      }
  });


});
</script>

</html>

Mail_Alert/mailalert/templates/reset_request.html
{% extends "layout_without_navbar.html" %}
{% block content %}
<div class="mx-auto" style="width:500px">
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                <div class="form-group">
                    
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
</div>

{% endblock content %}

Mail_Alert/mailalert/templates/resubscribed.html
{% extends "layout_without_navbar.html" %}
{% block content %}
<div class="text-center">
    <img class="unsubscribed-img" src="{{ url_for('static', filename='../static/logo-dark.png') }}" alt="Mail Alert">
    <p style="font-size: 15px">You have successfully resubscribed to receive package update information.</p>
</div>
{% endblock content %}